# Funding configuration for multiai
# Supported funding model platforms

github: [lrochetta]
# patreon: # Uncomment to add Patreon
# open_collective: # Uncomment to add Open Collective
# ko_fi: # Uncomment to add Ko-fi
# tidelift: # Uncomment to add Tidelift
# community_bridge: # Uncomment to add Community Bridge
# liberapay: # Uncomment to add Liberapay
# issuehunt: # Uncomment to add IssueHunt
# otechie: # Uncomment to add Otechie
# custom: ['https://rochetta.fr']
