version: "2"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - unparam
    - prealloc
    - nakedret

linters-settings:
  gosec:
    excludes:
      - G104
  misspell:
    locale: US

run:
  timeout: 5m
  tests: true
