#!/usr/bin/env bash
# -------------------------------------------------------------------
# generate-wrappers.sh — Generates per-profile shortcut wrappers
#
# Reads all .env profiles from MULTIAI_PROFILES_DIR (defaults to
# multiai-go/internal/assets/profiles/), extracts the SHORTCUT= value
# from each, and writes executable bash (Linux/macOS) and .cmd
# (Windows) wrappers into the output directory.
#
# Usage:
#   bash scripts/generate-wrappers.sh
#   MULTIAI_PROFILES_DIR=multiai-go/internal/assets/profiles bash scripts/generate-wrappers.sh
#   WRAPPER_OUTPUT_DIR=build/wrappers bash scripts/generate-wrappers.sh
# -------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---- Configuration ------------------------------------------------
PROFILES_DIR="${MULTIAI_PROFILES_DIR:-"$REPO_ROOT/multiai-go/internal/assets/profiles"}"
OUTPUT_DIR="${WRAPPER_OUTPUT_DIR:-"$REPO_ROOT/wrappers"}"
MULTIAI_CMD="${MULTIAI_CMD:-multiai}"

# Resolve the complete destination and refuse roots or symlink destinations.
# Cleanup below removes only wrapper files owned by this generator; it never
# recursively deletes the selected directory.
if [ -L "$OUTPUT_DIR" ]; then
    echo "Refusing symlink wrapper output: $OUTPUT_DIR" >&2
    exit 1
fi
mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR="$(cd "$OUTPUT_DIR" && pwd -P)"
case "$OUTPUT_DIR" in
    /|"$REPO_ROOT"|"${HOME:-__unset_home__}")
        echo "Refusing unsafe wrapper output: $OUTPUT_DIR" >&2
        exit 1
        ;;
esac

generated_count=0
error_count=0

# ---- Clean & prepare output ---------------------------------------
find "$OUTPUT_DIR" -maxdepth 1 -type f -name 'multiai-*' -delete

echo "Reading profiles from: $PROFILES_DIR"
echo "Writing wrappers to:  $OUTPUT_DIR"
echo ""

# ---- Iterate over .env profiles -----------------------------------
for envfile in "$PROFILES_DIR"/*.env; do
    [ -f "$envfile" ] || continue

    basename_env=$(basename "$envfile" .env)

    # Extract SHORTCUT value (first occurrence, strip optional quotes)
    shortcut=$(grep -m1 "^SHORTCUT=" "$envfile" 2>/dev/null | sed 's/^SHORTCUT=//' | sed 's/^"//;s/"$//' | sed "s/^'//;s/'$//" || true)

    if [ -z "$shortcut" ]; then
        echo "  [SKIP] $basename_env — no SHORTCUT found"
        error_count=$((error_count + 1))
        continue
    fi

    # Sanitize shortcut for use as a filename (replace non-alphanumeric chars with hyphen)
    safe_shortcut=$(echo "$shortcut" | sed 's/[^a-zA-Z0-9_-]/-/g')

    # ---- Bash wrapper (Linux / macOS / Git-Bash) -------------------
    bash_file="$OUTPUT_DIR/multiai-$safe_shortcut"
    cmd_file="$OUTPUT_DIR/multiai-$safe_shortcut.cmd"
    if [ -L "$bash_file" ] || [ -L "$cmd_file" ]; then
        echo "  [ERROR] refusing wrapper symlink for $shortcut" >&2
        error_count=$((error_count + 1))
        continue
    fi
    cat > "$bash_file" <<-WRAPPER
	#!/usr/bin/env bash
	# Wrapper for profile "$shortcut" ($basename_env)
	# Generated by scripts/generate-wrappers.sh
	exec $MULTIAI_CMD launch -p "$shortcut" "\$@"
	WRAPPER
    chmod +x "$bash_file"

    # ---- Windows .cmd wrapper -------------------------------------
    cat > "$cmd_file" <<-WRAPPER
	@echo off
	REM Wrapper for profile "$shortcut" ($basename_env)
	REM Generated by scripts/generate-wrappers.sh
	$MULTIAI_CMD launch -p "$shortcut" %*
	WRAPPER

    echo "  [OK]   $shortcut → multiai-$safe_shortcut, multiai-$safe_shortcut.cmd"
    generated_count=$((generated_count + 1))
done

# ---- Summary ------------------------------------------------------
echo ""
echo "----------------------------------------"
echo " Generated: $generated_count wrapper pair(s)"
echo " Errors:    $error_count"
echo " Output:    $OUTPUT_DIR"
echo "----------------------------------------"
