version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/multiai-go"
    schedule:
      interval: "weekly"
    assignees:
      - "lrochetta"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "lrochetta"

  - package-ecosystem: "npm"
    directory: "/multiai-powershell"
    schedule:
      interval: "weekly"
